### ISSUE TITLE
url.cn生成失效了么？

### ISSUE THREAD

**Issue by xingline** [lufei/notes#1]
https://vip.video.qq.com/fcgi-bin/comm_cgi?name=short_url&need_short_url=1&url=https://notes.qq52o.me
直接访问 没出来短网址谢谢

**Comment by sy-records** [comment]
好像是挂了。。加了csrf

**Comment by xingline** [comment]
好的谢谢

**Comment by sy-records** [comment]
可以用`w.url.cn`，等会更新下
https://w.url.cn/s/APh0D7m

**Comment by xingline** [comment]
好的谢谢，厉害了

**Comment by sy-records** [comment]
更新了 1498b8dd

**Comment by xingline** [comment]
Q多少，加下好友有个小需求付费解决，谢谢

**Comment by sy-records** [comment]
85464277

**Comment by sy-records** [comment]
可以使用，增加refer即可。
